@baseUrl = http://localhost:3001/maple
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG5leG9uLmNvbSIsInN1YiI6IjY4MmEyMDNmMjIwZDkzY2UwOTA2MzJlYyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzU5MTk2NywiZXhwIjoxNzQ3NTk1NTY3fQ.N4_J8G2G8PgX1_UCqY-wnImgMGCJN7fRHjtQ7d1Kb1I
@tokenUser1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQG5leG9uLmNvbSIsInN1YiI6IjY4MmEyMDQ4MjIwZDkzY2UwOTA2MzJmMiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQ3NTkxOTgzLCJleHAiOjE3NDc1OTU1ODN9.8hI5Y-YGK1nVizWByNO1B_MR_QDtiCIl9z_VHB0-NDk
@tokenUser2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQG5leG9uLmNvbSIsInN1YiI6IjY4MmEyMDQyMjIwZDkzY2UwOTA2MzJlZiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQ3NTkxOTk3LCJleHAiOjE3NDc1OTU1OTd9.Rp8bZ59rkik9shHEGAtE9HvyHad2oYK4w1jfoq-N6Us

### 1. 사용자 전체 조회
GET {{baseUrl}}/auth/users/
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

### 1-1. 사용자 생성(USER)
POST {{baseUrl}}/auth/users/
Content-Type: application/json

{
    "role": "USER",
    "email": "user1@nexon.com",
    "password": "user1",
    "name": "유저1",
    "phone": "010-1234-5678",
    "age": 25
}

### 1-2. 사용자 생성(ADMIN)
POST {{baseUrl}}/auth/users/
Content-Type: application/json

{
    "role": "ADMIN",
    "email": "admin@nexon.com",
    "password": "admin",
    "name": "admin",
    "phone": "010-8765-4321",
    "age": 20
}

### 1-번외. 사용자 생성(AUDITOR)
POST {{baseUrl}}/auth/users/
Content-Type: application/json

{
    "role": "AUDITOR",
    "email": "auditor@nexon.com",
    "password": "auditor",
    "name": "auditor",
    "phone": "010-8765-4321",
    "age": 21
}

### 1-번외. 사용자 생성(OPERATOR)
POST {{baseUrl}}/auth/users/
Content-Type: application/json

{
    "role": "OPERATOR",
    "email": "operator@nexon.com",
    "password": "operator",
    "name": "operator",
    "phone": "010-8765-4321",
    "age": 21
}

### 2-1. 로그인 - USER
POST {{baseUrl}}/auth/users/login
Content-Type: application/json

{
    "email": "user1@nexon.com",
    "password": "user1"
}

### 2-2. 로그인 - ADMIN
POST {{baseUrl}}/auth/users/login
Content-Type: application/json

{
    "email": "admin@nexon.com",
    "password": "admin"
}

### 3-1. 캐릭터 전체 정보 조회
GET {{baseUrl}}/auth/characters

### 3-2. 캐릭터 생성
POST {{baseUrl}}/auth/characters
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

{
  "nickname": "ayo1"
}

### 3-3. 캐릭터 레벨 및 아케인 포스 설정
PATCH {{baseUrl}}/auth/characters/nickname/tester2
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "level": 50,
  "arcaneForce": 900
}

### 4-1. event 조회
GET {{baseUrl}}/event/admin/
Authorization: Bearer {{tokenAdmin}}

### 4-2. event 등록
POST {{baseUrl}}/event/admin/add
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
  "title": "2025 대규모 업데이트",
  "subTitle": "레벨 올리기!",
  "option": "level",
  "eventLevel": 0,
  "destination": 100,
  "description": "100레벨을 달성하라!",
  "deadline": "2024-06-01T23:59:59.000Z"
}

### 4-3 이벤트에 보상 추가 (title, subTitle로)
POST {{baseUrl}}/event/admin/addRewardByTitle
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "title": "2025 대규모 업데이트",
  "subTitle": "레벨 올리기!",
  "rewardNm": "심볼",
  "rewardCount": 2
}

### 5-1.보상 신청 목록 확인
GET {{baseUrl}}/event/reward
Authorization: Bearer {{tokenAdmin}}

### 5-2.이벤트 보상 신청
POST {{baseUrl}}/event/reward
Authorization: Bearer {{tokenUser1}}
Content-Type: application/json

{
  "nickname": "ayo1",
  "title": "2025 대규모 업데이트",
  "subTitle": "레벨 올리기!"
}

### 6-1. 보상 부여
POST {{baseUrl}}/event/reward/check
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "nickname": "ayo1",
  "title": "2025 대규모 업데이트",
  "subTitle": "레벨 올리기!"
}

### 6-2. 내 이벤트 가져오기
GET {{baseUrl}}/event/reward/my
Authorization: Bearer {{tokenUser1}}
