@baseUrl = http://localhost:3002/maple
@userId = 6825d71ff2466726ac494222
### 1. 사용자 생성 테스트
POST {{baseUrl}}/users
Content-Type: application/json

{
    "role": "ADMIN",
    "email": "admin@example.com",
    "password": "admin",
    "name": "운영자",
    "phone": "010-1234-5678",
    "age": 25
}
// admin 계정: admin@example.com | admin
### 2. 모든 사용자 조회
GET {{baseUrl}}/auth/users

### 3. 특정 사용자 조회
# {userId} -> user 'user _id'
GET {{baseUrl}}/users/{{userId}}

### 4. 사용자 정보 수정
# 아래 {userId}는 사용자 생성 후 받은 ID로 교체해야 합니다
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
    "name": "수정된 이름",
    "age": 26
}

### 5. 사용자 삭제
DELETE {{baseUrl}}/auth/users/6825d71ff2466726ac494222

### 6. 잘못된 이메일 형식으로 사용자 생성 테스트
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "invalid-email",
    "password": "test1234",
    "name": "테스트 유저",
    "age": 25
}

### 7. 부적절한 나이로 사용자 생성 테스트
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "test12232@example.com",
    "password": "test1234",
    "name": "테스트 유저3",
    "age": 13
}

### 2. 로그인
POST {{baseUrl}}/auth/users/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin"
}